travis:
  secure:
    BINSTAR_TOKEN: bULen2tmXjDz9TvXgVqqU+tTvkIg8oSdwPTU1fPt3coRALF5pduT8L6/nPJPv6LayUg+ngyKdZ+VJHZfMw3vuXsPfDuQydRzxYjhvUMDM5S/TNqxyRE4+OpAp6kH+1XkSn2yzg6hyyLhWKhUQN07FRVUbesDBB9843CdyIfAax8fjjPe7pss7v4fSEIbDEr8mTaBavM/ugdhr2J+rbXocS38lVG6WO/7qs1HrzfGCmAXxS0bK9F0EB1H94EaHrEgDQ6y98+y5pDZ1EXOHoo/We2WKUfRrOX7WBapgX1yI21gqeLZQMW+ZYJterLV+Gxj45mjJg96z1btNsgoM0n8FATTezYTpE41Oj5mdJZMJ1DK5Gww9lMtXRQS1Wa/6WXsg6VUtU/2qinJ6WjvSM8NH2BWUNzgbmJkydIaNpFGu5Fynno+02ruHI0+0TRaHdZf29NZDbzL8wsjewdpDbo8jFiTrym9AKajmmo4rTEAKkj8B4qZ8qr6fmZGlq/jehsweEOUixNuUDi+3Q8IzPSg8yV97BbCcMGoWsymQ9GHdTe8bg5NEUTjr56/0PFtMK36QSx5X83gRkiUyHm432IzNfGDFeUh+8+y9xthXq/ZaluyrDLXCODFsCPaOcI/iINzRN5V06j10+Uew1j+JLwYRjFnlWJMuQBmvO8/gLaL1KA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
